import express from "express";
import authMiddleware from "./middleware/authMiddleware.js";
import questionRoute from "./routes/questionRoute.js";
import userRoute from "./routes/userRoute.js";
import cors from "cors";
const app = express();
app.use(cors());
app.use(express.json());
app.use("/api/v1/users/", userRoute);
app.use("/api/v1/questions/", authMiddleware, questionRoute);
export default app;
